services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend
    
  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    restart: always
    ports:
      - "5540:5540"
    depends_on:
      - redis
    networks:
      - backend

  server:
    container_name: server
    build: .
    environment:
      - REDIS_HOST=redis
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - backend

  nginx:
    image: nginx:1.25.3-alpine
    container_name: nginx
    restart: always
    ports:
      - "8003:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./:/usr/share/nginx/html
    networks:
      - backend

volumes:
  redis-data:

networks:
  backend:
    driver: bridge